name: CI Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR to OSS
        uses: manyuanrong/setup-ossutil@v3.0
        with:
          endpoint: oss-cn-beijing.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - run: ossutil cp target/test-1.0.jar oss://zhixiaotian-test/zhixiaotian/test-1.0.jar -f

      - name: Upload JAR to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 115.190.64.160
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: target/test-1.0.jar
          target: /home